### ISSUE TITLE
No filename option

### ISSUE THREAD

**Issue by josacar** [wercker/step-kubectl#19]
When using `rolling-update` `filename` argument should be used and `file` attribute doesn't work. 

This is the error:

```
Running kubctl command
Error: unknown flag: --file


Aliases:
rolling-update, rollingupdate
```

```yaml
- kubectl:
  certificate-authority: ca.pem
  token: $KUBERNETES_TOKEN
  command: rolling-update croc-hunter
  file: croc-hunter-controller.yml
```
